"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.syncMain = exports.syncRenderer = exports.bridge = exports.proxy = void 0;
var preload_1 = require("./preload");
Object.defineProperty(exports, "proxy", { enumerable: true, get: function () { return preload_1.proxy; } });
Object.defineProperty(exports, "bridge", { enumerable: true, get: function () { return preload_1.bridge; } });
var renderer_1 = require("./renderer");
Object.defineProperty(exports, "syncRenderer", { enumerable: true, get: function () { return renderer_1.syncRenderer; } });
var main_1 = require("./main");
Object.defineProperty(exports, "syncMain", { enumerable: true, get: function () { return main_1.syncMain; } });
